@echo off
cd /d "C:\Users\Nitropc\Desktop\web-navride\web-navride"
echo Eliminando index.lock...
del /f /q ".git\index.lock" 2>nul
echo Ejecutando git add...
git add -A
echo Ejecutando git commit...
git commit -m "feat: panel policial, perfil, GPX save API, Supabase fixes, middleware auth"
echo Ejecutando git push...
git push
echo.
echo Proceso completado. Pulsa cualquier tecla para cerrar.
pause
